debug:
server:
  port: 9999

security:
  sessions: ALWAYS
  user:
    password: user
# ignored: /favicon.ico,/index.html,/home.html,/dashboard.html,/js/**,/css/**,/webjars/**
# management:
#   security:
#     role: HERO

logging:
  level:
    org.springframework.security: DEBUG
    com.netflix.discovery: 'OFF'

zuul:
  routes:
    kibana:
      path: /**
      url: http://logs.54.183.203.97.xip.io

cloudfoundry:
  cloudControllerUri: http://api.run.54.183.203.97.xip.io
  uaaUri: http://uaa.run.54.183.203.97.xip.io

logsearch:
  elasticsearchAdminUri: http://127.0.0.1:9200

spring:
  oauth2:
    sso:
      loginPath: /login
      logoutPath: /logout
    client:
      accessTokenUri: http://login.run.54.183.203.97.xip.io/oauth/token
      userAuthorizationUri: http://login.run.54.183.203.97.xip.io/oauth/authorize
      clientId: logsearch_for_cloudfoundry-dev
      clientSecret: "XXXXXXX"
      scope: "openid,scim.userids,cloud_controller.read"
    resource:
      jwt:
        keyUri: http://uaa.run.54.183.203.97.xip.io/token_key
      id: openid
      serviceId: ${PREFIX:}resource